language: python
python:
  - 3.8.1
env:
  matrix:
  - secure: b+rPEJWotTzJxzN+7FpCRuVthFu8occtrDZp7g23ldV4IIGwjd38cBJ7OIa7NIsO347eldZaZe63v1F2bIY7+k9oc58MlRGluereMCCNhB0nOGvcA3mWRYgSnGaxT0AwgbnaFN5k20U2ZAPLxuH46BenHrIeHSU7qpuY6P1NXUK3H8r4fCVVZJ2e0p7AJ/W30Bt9ISYdRsQ+2v0sSbsIeFOMlYWwtZE4ZvfiPYKCBwud1rEWm56ZA0bnkRlvDiBNnCziG54uqehD8Ur03bHMygP6/PbvvqTpdGyCZ4unDQaNPsYBzo86/k5dFyiYpWdvU0ZodVTnKjBiLBcTJ7UIcSFSH9p2mMhdWSBkcSi59C/wSylw81cS8SGfMYdaP4D8RJ0zZFyJiI2pNY6k6LPdnQmwZgqHdpwUdtYcWaMOy29som9HxUk6NBQWhbTMPkGNRZZtJA4MtMl+j8xSfejvF7YJeYPIqMVq8qFkCBqNu2p8RxjDcItnVOG1Ua2usEM6WA3LJOhh2Vj3cAjnI7oULlpHrRbSMie7rSIF8vacB9b2WMItyzUH+F4z25mHv+oK3isgbs0/gbdqYjIDsz3AFfYBG2AND0NXLykKNvoi8BcklxyZxlvPYb96WFYwXxEJ02Tmgfihub7gt9DBvV32vNXLJpa2s/j03XThyZ0n+YI=
before_install:
- chmod +x ./.deploy_scripts/tlsetup.sh
- ./.deploy_scripts/tlsetup.sh
install:
- pip install -r requirements.txt
script:
- make deploy
- make pdf
after_success:
- cp ./_build/latex/Aid_from_the_Air.pdf ./_build/html/Aid_from_the_Air.pdf
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: false
  on:
    branch: publish
  local_dir: _build/html
